package com.herve.ocgames.core.interfaces;

import com.herve.ocgames.utils.Response;

public interface CodeCheckerInterface {

    /**
     * Do evaluation after user attempt in challenger mode
     * @param attempt player attempt
     * @param secret secret code generated by computer
     * @return Response object (contains return code, error and applicative messages and a map<String,Object>
     */
    Response generateEvaluation(String attempt, String secret);

    /**
     * Check if User evaluation is correct
     * @param submittedEvaluation evaluation of computer attempt by player
     * @param refereeEvaluation computer must evaluate his own attempts to check if user evaluation is right
     * @return Response object (contains return code, error and applicative messages and a map<String,Object>
     */
    Response askRefereeControl(String submittedEvaluation, String refereeEvaluation);

    /**
     * Get evaluation from player in mode defender
     * @return Response object (contains return code, error and applicative messages and a map<String,Object>
     */
    Response askPlayerEvaluation();

}
